# This is a basic workflow to help you get started with Actions

name: CI/CD with Terraform
on:
  push:
    branches: [ "main" ]

env:
  CONFLUENT_CLOUD_API_KEY: ${{ secrets. }}
  CONFLUENT_CLOUD_API_SECRET: ${{ secrets. }}
  AWS_ACCESS_KEY_ID: ${{ secrets. }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets. }}
  TF_STATE_BUCKET_NAME: ${{ secrets. }}
  
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=us-east-1"
        working-directory: ./terraform
      - name: Terraform Plan
        id: plan
        run: |-
          terraform plan \  
          -var="confluent_cloud_api_key=$confluent_cloud_api_key"
          -var="confluent_cloud_api_secret=$confluent_cloud_api_secret"
          -out=PLAN
        working-directory: ./terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform
